### PR TITLE
Fix setup install

### PR DESCRIPTION
**Pull request by langep**
I ran into problems when calling `python setup.py install` as part of an effort to create a conda package out of sequitur-g2p. For some reason `sequitur_.py` which is generated by SWIG wasn't included in the package.

It seems that building the SWIG extension generated python module for some reason wasn't done in the correct order. This is likely because the order was only fixed for the "build" command but not the "install" command inside setup.py.

Instead of changing the order for the whole build command, I followed https://stackoverflow.com/questions/29477298/setup-py-run-build-ext-before-anything-else/48942866#48942866 and modify that step for building python modules to first call the extension.

I tested that `pip install git+https://github.com/sequitur-g2p/sequitur-g2p@master` would still work for python2.7 and 3.6 and newer.

Sorry about the changes to the quoting done by the formatter. I could revert these if desired.

### CODE REVIEW

**Comment by jtrmal** [comment]
yes, could you please change it back?
y.

**Comment by langep** [comment]
I reverted the changes to the quoting style but also saw that some of the original line breaks got removed. I am working on restoring those.

**Comment by langep** [comment]
Ok, I removed all the formatting changes so the PR only contains meaningful changes.

**Comment by jtrmal** [comment]
Sorry, I forgot about this. Thanks! Merging

**Pull request merged**
