### PR TITLE
memory-leak fix

### PR DESCRIPTION
**Pull request by manickavela29**
Hi @jtrmal,
-- memory leak fix by object handling with shared_pointer.

Author: @uni-kadri

### CODE REVIEW

**Comment by jtrmal** [comment]
Nice, give me please a few days to check this. But looks good, IMO.

**Comment by manickavela-uni** [comment]
cc: @pavankumar-ds

**Comment by manickavela29** [comment]
cc : @pavankumar-ds

**Comment by jtrmal** [comment]
One quick observation is that you replaced intrusive pointer by non-intrusive, which might increase memory consumption. Not sure by how much -- and in a memory-leak state, this most certainly will improve it :)

**Comment by manickavela29** [comment]
yes @jtrmal, @kadri-uni has updated such that rather taking libraries intrusive pointer implementation, it will have a shared pointer for doing the same.

Ideally there shouldn't be much increase in memory usage w.r.t pointer reference usage,
Even though functionally similar, shared_pointer is just going to use a separate block for holding its self. I doubt its memory will grow, as only reference count is going to get increased.

@kadri-uni can comment better.

**Comment by jtrmal** [comment]
Hi, looks good, merging

**Review by jtrmal — APPROVED** [review]

**Comment by manickavela29** [comment]
Hi @jtrmal ,
It would also be great to have a release with this patch

**Comment by jtrmal** [comment]
I'm working on it, but there are a lot of things that have changed outside
this repo -- numpy 2.0, github actions and so on
y.

**Pull request merged**
