### PR TITLE
Fix fsa -- review of the PR

### PR DESCRIPTION
**Pull request by jtrmal**
replaces/supersedes #53

### CODE REVIEW

**Comment by jtrmal** [comment]
@svecjan can you please test on your use case if this is producing the expected results?

**Comment by svecjan** [comment]
Tested, but I had still a problem with `streamWriter` but I prepared a patch that fixes it.
[0001-Fix-fsa-output-stream.patch.zip](https://github.com/sequitur-g2p/sequitur-g2p/files/4161582/0001-Fix-fsa-output-stream.patch.zip)

**Comment by jtrmal** [comment]
Thanks, will get that included today (hopefully)
y.

**Comment by jtrmal** [comment]
Merging

**Pull request merged**
